modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"
issueTrackerURL="https://github.com/Yesssssman/epicfightmod/issues" #optional
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod" #optional
logoFile="epicfight_logo.png" #optional
credits="METAL, SAGESSE, Nathan" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies.epicfight]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47.2.20,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.epicfight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
